import typer
from text2sql_rag.retrieval import Retriever
from text2sql_rag.prompt import build_prompt
from text2sql_rag.llm import call_typhoon
from text2sql_rag.run_query import run_sql_on_csv
from tabulate import tabulate app = typer.Typer()
retriever = Retriever() @app.command()
def ask( question: str = typer.Option(None, "--question", "-q", help="คำถามภาษาไทยที่จะใช้ generate SQL"), top_k: int = typer.Option(5, "--top-k", help="จำนวน context schema ที่ใช้"), run: bool = typer.Option(False, "--run", help="ให้รัน SQL หรือไม่"), show_schema: bool = typer.Option(False, "--show-schema", help="แสดง context schema ที่ใช้ก่อนถาม LLM")
    """Ask function"""

): if question is None: question = input("กรุณากรอกคำถาม: ") try: context = retriever.query(question, top_k) few_shot_examples = '''\nตัวอย่าง:\nคำถาม: แสดงชื่อผู้ป่วยที่มีโรคเบาหวาน\nSQL:\nSELECT Name FROM patients WHERE "Medical Condition" = 'Diabetes';\n\nคำถาม: แสดงชื่อและอายุของผู้ป่วยที่เข้ารักษาแบบ Urgent\nSQL:\nSELECT Name, Age FROM patients WHERE "Admission Type" = 'Urgent';\n\nคำถาม: แสดงชื่อผู้ป่วยและแพทย์ผู้ดูแลที่มีผลตรวจเป็น Abnormal\nSQL:\nSELECT Name, Doctor FROM patients WHERE "Test Results" = 'Abnormal';\n\nคำถาม: แสดงชื่อผู้ป่วยและค่าใช้จ่ายที่มีอายุมากกว่า 60 ปี\nSQL:\nSELECT Name, "Billing Amount" FROM patients WHERE Age > 60;\n\nคำถาม: แสดงชื่อผู้ป่วยที่อายุมากที่สุด\nSQL:\nSELECT Name FROM patients ORDER BY Age DESC LIMIT 1;\n\nคำถาม: แสดงจำนวนผู้ป่วยแต่ละโรค\nSQL:\nSELECT "Medical Condition", COUNT(*) FROM patients GROUP BY "Medical Condition";\n\nคำถาม: แสดงชื่อผู้ป่วย 5 คนแรกที่เข้ารักษา\nSQL:\nSELECT Name FROM patients ORDER BY "Date of Admission" ASC LIMIT 5;\n\nคำถาม: แสดงชื่อผู้ป่วยและโรงพยาบาลที่มีค่าใช้จ่ายรวมมากกว่า 100,000 บาท (GROUP BY + HAVING)\nSQL:\nSELECT Hospital, SUM("Billing Amount") as Total FROM patients GROUP BY Hospital HAVING Total > 100000;\n\nคำถาม: แสดงชื่อผู้ป่วยและโรคที่มีผู้ป่วยมากกว่า 1000 คน (GROUP BY + HAVING)\nSQL:\nSELECT "Medical Condition", COUNT(*) as cnt FROM patients GROUP BY "Medical Condition" HAVING cnt > 1000;\n\nคำถาม: แสดงชื่อผู้ป่วยและชื่อแพทย์ที่ดูแล (JOIN แบบสมมติ)\nSQL:\n-- สมมติว่ามีตาราง doctors (DoctorID, DoctorName)\nSELECT p.Name, d.DoctorName FROM patients p JOIN doctors d ON p.Doctor = d.DoctorName;\n\nคำถาม: แสดงชื่อผู้ป่วยที่มีค่าใช้จ่ายสูงสุดในแต่ละโรงพยาบาล (SUBQUERY)\nSQL:\nSELECT Name, Hospital, "Billing Amount" FROM patients WHERE (Hospital, "Billing Amount") IN (SELECT Hospital, MAX("Billing Amount") FROM patients GROUP BY Hospital);\n\nคำถาม: แสดงชื่อผู้ป่วยและข้อความสรุปว่า "สูงวัย" ถ้าอายุมากกว่า 60 ปี (CASE WHEN)\nSQL:\nSELECT Name, CASE WHEN Age > 60 THEN 'สูงวัย' ELSE 'ทั่วไป' END AS AgeGroup FROM patients;\n''' prompt = build_prompt(context, question, few_shot_examples=few_shot_examples) sql = call_typhoon(prompt) print("\nSQL ที่ LLM สร้าง:") print(sql) if run: cols, rows = run_sql_on_csv(sql) print("\nผลลัพธ์:") print(tabulate(rows, headers=cols, tablefmt="grid")) except Exception as e: print("เกิดข้อผิดพลาด:", e) if __name__ == "__main__": app()
